services:
  app:
    image: node:lts@sha256:20988bcdc6dc76690023eb2505dd273bdeefddcd0bde4bfd1efe4ebf8707f747
    ports:
      - 4321:4321
    working_dir: /app
    command: npm run dev -- --host 0.0.0.0
    volumes:
      - ./:/app
